// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unscypzpttcuzxqhcldc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuc2N5cHpwdHRjdXp4cWhjbGRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTg5ODcsImV4cCI6MjA2NDA5NDk4N30.Hf586npG5tsGp0JOLN3NTB0LkTnP4LevKcYHt0Xpe-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);